### ISSUE TITLE
CSV subject line not correct

### ISSUE THREAD

**Issue by mhguidry** [bluekeyes/Fusion360-ExportCutlist#13]
Very much appreciate the effort in producing the code. Thank you.
I've just installed latest version and noticed a difference between table output and csv output. Table is correct.
Here is what I an seeing....
CSV file
![image](https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/33076812/d1ff1e99-f80a-41bc-9f16-83850d2904c6)
TABLE file
![image](https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/33076812/9e632b0e-75e0-4b84-8a34-8582f91c56c3)

**Comment by mhguidry** [comment]
Problem might be here...
![image](https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/33076812/c0c4eb7a-a6b2-48e4-afe6-723287701354)
Notice order

**Comment by bluekeyes** [comment]
Thanks for reporting this, looks like I messed up the order while refactoring in b9cae3ead6c03748a249d737601e7e380cc5a655. I'll try to release a fix in the next day or two.

**Comment by bluekeyes** [comment]
This should be fixed in the latest version, [v0.4.1](https://github.com/bluekeyes/Fusion360-ExportCutlist/releases/tag/v0.4.1)
