### ISSUE TITLE
Install Confusing Instructions - Doesn't Show in "Make" dropdown after install

### ISSUE THREAD

**Issue by DPBest** [bluekeyes/Fusion360-ExportCutlist#14]
I am a woodworker and would love this capability in F360.  However I am not a programmer or familiar with the details of how to install this thing.  I did as described, but found out I had to "Create" an add-on (which isn't described in the install instructions).  It appears to be installed and running, but I the add-on is not listed in the pull-down under the "Make" menu.  HELP!!

**Comment by bluekeyes** [comment]
Hey @DPBest, sorry you had trouble installing this. Here's a more detailed explanation with screenshots:

1. Download the [latest release](https://github.com/bluekeyes/Fusion360-ExportCutlist/archive/v0.4.1.zip)
2. Unzip the file on your computer
3. In Fusion 360, open the "Scripts and Add-in" dialog under the "Add-ins" menu in the "Utilities" tab:
   <img width="652" alt="scripts_and_addins" src="https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/1745813/792770ac-3ea1-4a7a-90ee-2fece296fc7a">
4. Click on the "Add-Ins" tab and the click on the green "+" sign:
   <img width="333" alt="green_plus" src="https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/1745813/be81c2e9-725c-40d6-b118-c46d9a9085df">
5. Browse to the location from Step 2 and select the directory:
   <img width="719" alt="select_directory" src="https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/1745813/fdc14e73-0d93-4226-b7e4-ed1daf1663ee">
6. Now, with "ExportCutlist" selected, click the "Run" button (or restart Fusion 360):
   <img width="324" alt="run" src="https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/1745813/1e79d8e7-a63c-45e9-85b1-1ea5359565e9">
7. When the add-in is running, you will see a circle of dots next to the name:
   <img width="95" alt="running" src="https://github.com/bluekeyes/Fusion360-ExportCutlist/assets/1745813/7bfe6b98-1908-44b0-883e-e611f51dc3d1">

At this point, you should be able to find the option in the "Make" menu.

**Comment by DPBest** [comment]
Wow - what a difference these instructions make.  I was able to get this installed and working.  What tripped me up with the add-ins tab - I didn’t see the green + symbol, and figured thus that I had to “Create":

https://user-images.githubusercontent.com/1745813/250719091-be81c2e9-725c-40d6-b118-c46d9a9085df.png

This is a wonderful add-on for us Woodworkers.  Being able to send the parts list off to a layout package is really valuable.  Thank you for doing this.

Now, if the cultist applications were more intuitive, I’d be in nirvana.  :-)

David Best

**Comment by bluekeyes** [comment]
Great, glad everything is working now!

**Comment by DPBest** [comment]
Now that I've used it I have a question and a feature request.

The question is this:  If a component is created with the Mirror command, is it consider a distinct and different part from it's source component?  In the Drawing Parts List tables, mirrored components are treated as distinct parts rather than the second copy of the original.  This clutters the parts lists.

Feature improvement request:  I would like the option to generate output with one part per line (rather than grouping all parts of the same dimension into a quantity bucket) where each line has the Name of the particular component from the Model.  As it is now, the Name of a group of identical components shows up as a long string of the components that are combined.  This makes it difficult to create a cut-list where each part is named specifically as it is named in the model.

Thanks again for doing this.

David

**Comment by bluekeyes** [comment]
> If a component is created with the Mirror command, is it consider a distinct and different part from it's source component? In the Drawing Parts List tables, mirrored components are treated as distinct parts rather than the second copy of the original. This clutters the parts lists.

In general, yes. The add-in does not know about the operations you used to create the different bodies, so it treats each selected body as a separate part. Since mirrored bodies should have the same dimensions, these would be grouped together in a single line in the output cutlist with a quantity greater than one. Grouping parts with the same dimensions is the main way the add-in tries to reduce clutter.

> Feature improvement request: I would like the option to generate output with one part per line (rather than grouping all parts of the same dimension into a quantity bucket) where each line has the Name of the particular component from the Model. As it is now, the Name of a group of identical components shows up as a long string of the components that are combined. This makes it difficult to create a cut-list where each part is named specifically as it is named in the model.

This is a good idea - I've created #15 to track adding this feature.
