### ISSUE TITLE
Add option to disable dimension grouping

### ISSUE THREAD

**Issue by bluekeyes** [bluekeyes/Fusion360-ExportCutlist#15]
From #14:

> I would like the option to generate output with one part per line (rather than grouping all parts of the same dimension into a quantity bucket) where each line has the Name of the particular component from the Model. As it is now, the Name of a group of identical components shows up as a long string of the components that are combined. This makes it difficult to create a cut-list where each part is named specifically as it is named in the model.

**Comment by DPBest** [comment]
Just to emphasize this a bit, there are several application programs that take a parts list, do a layout, then produce cut diagrams that caan have the name of each part on the diagram, which can then be printed out for cutting in the shop.  Some of these applications also spit out labels that can be affixed to the parts as they are cut to aid in identification during assembly.  When I'm doing a kitchen for example, I might have 200 parts all cut in one session with the panel saw.  To get this kind of part identification in the layout diagrams, each part needs to be a separate line item with the part name identified.  I'm glad you think this is a good idea.  I look forward to this facility and thank you profusely for your contribution on this.   If you want me to beta test, happy to do so.  Here is one example of this kind of applications output, driven by a CSV file where each part is an individual line in the CSV file:
[Multirouter Cart Drawing v8 Cutlist.pdf](https://github.com/bluekeyes/Fusion360-ExportCutlist/files/11952210/Multirouter.Cart.Drawing.v8.Cutlist.pdf)

Using your current add-on version, with all parts of the same size grouped together, the online Cutlist EVO site produces the following type of output.  As you can see, it's difficult to identify the name of each part and how it corresponds to the model and the Drawing part list produced by Fusion.
[cut list-3.pdf](https://github.com/bluekeyes/Fusion360-ExportCutlist/files/11952247/cut.list-3.pdf)

**Comment by bluekeyes** [comment]
I've added an option for this in [version 0.5.0](https://github.com/bluekeyes/Fusion360-ExportCutlist/archive/refs/tags/v0.5.0.zip) - if you uncheck the "Dimensions" option in the new "Group By" section, it will produce a cutlist where each part is a separate row. Please try it out and let me know if it works for you.

To upgrade the add-in version, I think the easiest way is to close Fusion 360, delete the folder for the old version from your computer, then follow the install instructions again to install the new version.
