### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mts749** [bluekeyes/Fusion360-ExportCutlist#18]
###

I am having trouble installing ExportCutlist. I followed the instructions but after selecting the folder "Fusion360-ExportCutlist-0.5.0" it fails to add it to the list in MyScipts and of course I can go no further. 

I'm running a Fusion360 beta release, perhaps that is the problem? Here is the environment:
> Fusion 360 2.0.16976 arm64 [Native] 
> macOS 13.5 (22G74) on MacBookPro18,1

Any ideas on next steps?

Thanks,
Martin

**Comment by bluekeyes** [comment]
Sorry if you already tried this, but I see you mentioned "My Scripts". Can you make sure you selected the "Add-ins" tab before trying to install this? There are also some screenshot of the process on the wiki, if you haven't seen them: https://github.com/bluekeyes/Fusion360-ExportCutlist/wiki/Installation

**Comment by mts749** [comment]
Boy, don't I feel dumb! That was it, thanks.
