### ISSUE TITLE
Export Cutlist 

### ISSUE THREAD

**Issue by deanforbes** [bluekeyes/Fusion360-ExportCutlist#7]
This is really a Enhancement or feature request - I see you are using labels or I would have marked it as such 

Your tool saved me a significant amount of time this evening - many thanks 

It would be fantastic if it remembered what format you have selected for your export 

Export Cutlist
.Table
.JSON
.CSV

**Comment by bluekeyes** [comment]
Thanks for the suggestion - the latest version (0.3.1) now remembers the selected options, including the format, between uses of the command. Note that each time you start Fusion 360, the options still reset to the default values, but hopefully this makes it easier if you're exporting multiple times from the same project.

**Comment by deanforbes** [comment]
You are a star - thank you
