### ISSUE TITLE
No bug, just thanks!

### ISSUE THREAD

**Issue by jwr** [bluekeyes/Fusion360-ExportCutlist#9]
No issue to report. I just wanted to thank you for writing this plugin and for making it available. It does the job very well, and is simple and straightforward. Fantastic work!

I'm using it with https://cutlistevo.com/ and it works great: I export a CSV, open it in Numbers and rearrange colums so that they fit one of the formats that CutlistEvo expects, and the data gets imported nicely.

**Comment by bluekeyes** [comment]
I'm glad you've found this plugin useful! Thanks too for sharing your workflow with CutlistEvo - I wasn't familiar with that tool and will have to try it out on a future project.
